### ISSUE TITLE
Resource punkt not found

### ISSUE THREAD

**Issue by EmporioAlnino** [2020-DL-Training-Program/Lab3-Image-Caption#1]
助教您好:

想請問一下我在執行$ python build_vocab.py之後會顯示 Resource punkt not found

但當我執行以下的command之後 
>>>import nltk
>>>nltk.download('punkt')

會顯示 "Error loading punkt : <urlopen error [Error 110] Connection timed out"

應該是工作站在連網上有一定限制的關係

想請問一下手動下載punkt比較詳細的步驟?

感謝

**Comment by meegoStar** [comment]
Hi @EmporioAlnino ,

I encountered the same issue on our team's local server too. Maybe you can give the following code snippet a try.
```
import nltk
import ssl


try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download('punkt')

```

**Comment by EmporioAlnino** [comment]
Hi @meegoStar,

感謝您的回覆

我後來嘗試了下列網站的方法似乎可以work

https://www.cnblogs.com/lovely7/p/6110878.html

**Comment by zivzone** [comment]
關於這塊可能還是需要去請 IT 幫忙，因為牽涉到內部 IT 管理 sever 的一些設定等等。
IT 可以幫忙關於 download punkt的部分
