### ISSUE TITLE
undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by EmporioAlnino** [2020-DL-Training-Program/Lab3-Image-Caption#3]
助教您好,

我在執行python3 train.py的時候會遇到 undefined symbol: _Py_ZeroStruct這樣的Error

看了以下的網頁我試著把Readme裡面第一步的makefile裡面的python改成python3

然後執行了步驟一

https://github.com/cocodataset/cocoapi/issues/90

但還是會遇到相同的問題

想請問一下助教這樣的問題有沒有排解的方法?

**Comment by zivzone** [comment]
助教個人再執行遇到這個問題時也是參考這個連結。但理論上應該不會遇到這個問題，因為之前請 IT 在 Sever 上測試是回報沒有問題，若還是遇到這個問題，可能需要詢問一下 IT 的指示，看看是不是有甚麼特別的設定等等。
