### ISSUE TITLE
Why we need to unpack sequence

### ISSUE THREAD

**Issue by Jenny338** [2020-DL-Training-Program/Lab3-Image-Caption#4]
助教您好
請問在DIY_LSTM.py裡，forward的部分，需要檢查input_seq是不是一個packed的sequence呢
這邊說的packed 是  pack_padded_sequence 做的那件事嗎

**Comment by zivzone** [comment]
@Jenny338 你好，是的，我們在 LSTM 的 forward 實作中通常應該加入判斷此時 input 的 data 是不是 packed 的 sequence ，這樣時做出來的 function 會比較 general 。但本此 lab 其實可以忽略這一步，因為 lab 中幫大家寫好要餵進 DIY_LSTM 的 data 是已經 packed 的了，所以就直接根據 packed 的 data 去寫要如何去撈資料是 OK 的。
如果要寫判斷，大概寫起來會長得像這樣:
```
is_packed = isinstance(input_seq, PackedSequence)
if is_packed:
	input_seq, batch_sizes = input_seq
	max_batch_size = batch_sizes[0].item()
	time_step = batch_sizes.shape[0]
			
else:
	batch_sizes = None
	max_batch_size = input_seq.shape[0] if self.batch_first else input_seq.shape[1]
	time_step = input_seq.shape[1] if self.batch_first else input_seq.shape[0] 

.
.
.
.

```
