### ISSUE TITLE
關於Report中的DEMO

### ISSUE THREAD

**Issue by jasperchang504** [2020-DL-Training-Program/Lab3-Image-Caption#5]
助教Report中的Demo是隨便輸入自己給的圖片嗎
然後demo中的question要寫什麼呢??

**Comment by zivzone** [comment]
@jasperchang504 你好，Demo 當天請使用助教提供的照片，檔案在 png 這個資料夾內。
"One or	two questions related to LSTM" 指的是助教在demo當天會問幾個關於 LSTM 相關的問題，這個部分的問題可以不用紀錄在 report 上，report 上關於這個部分僅需放上跑出來的結果即可。關於這個部分我們在 report spec 上的寫法可能會造成大家誤會，我們會再請 Chloe 轉達給其他人。

**Comment by Jenny338** [comment]
請問這次LAB只需要繳交Report就好，code的部分有需要附上嗎

**Comment by jasperchang504** [comment]
Hi Ziv,
但這樣報告配分只有80分
Report Spec
1. Introduction (5%)
2. Explain how you implement LSTM (45%)
3. Results – generating corresponding descriptions
A. example.png (10%)
B. ext.png (10%)
4. Discussion (10%)
5. Demo (20%)

**Comment by zivzone** [comment]
@Jenny338 你好，Code 還是要附上

**Comment by zivzone** [comment]
@jasperchang504 你好，感謝指出這個分數上的疑慮。我們在寄給 Chloe 的文件中會指出這一部分上的修正，會跟各位的 Lab2 成績表一併寄給 Chloe,預計各位在今天或者明天應該會拿到最新的這一部分。目前我們把 report 成績各部分占比修正為
```
Report Spec

1.Introduction (5%)
2.Explain how you implement LSTM (60%)
3.Results – generating corresponding descriptions
     A. example.png (10%)
     B. ext.png (15%)
4.Discussion (10%)
```
